name: CI – Build & Test

on:
  pull_request:
    branches:
      - main
      - QA
      - DEV

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias
        run: dotnet restore Usuarios/Usuarios.slnx

      - name: Compilar solución
        run: dotnet build Usuarios/Usuarios.slnx --configuration Release --no-restore

      - name: Ejecutar pruebas unitarias
        run: dotnet test Usuarios/Usuarios.slnx --configuration Release --no-build --verbosity normal
