name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Ensure init-db.sh is executable
        run: chmod +x init-db.sh

      - name: Build and deploy with Docker Compose
        run: docker compose up -d --build

      - name: Clean up old images
        run: docker image prune -f

      - name: Show running containers
        run: docker compose ps
